name: flex_color_picker
description: A customizable Flutter primary, accent and custom color picker. Includes an optional HSV wheel color picker.
version: 3.0.3
homepage: https://github.com/rydmike/flex_color_picker
repository: https://github.com/rydmike/flex_color_picker
issue_tracker: https://github.com/rydmike/flex_color_picker/issues
documentation: https://github.com/rydmike/flex_color_picker/blob/master/README.md
environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  # FlexSeedScheme package, by Mike Rydstrom, rydmike.com (@rydmike).
  # https://pub.dev/packages/flex_seed_scheme
  flex_seed_scheme: ^1.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  collection:
  flutter_test:
    sdk: flutter
  test:

flutter:
  uses-material-design: true
  assets:
    - assets/
